---
- name: Update web servers
  hosts: 34.218.227.195
 
  tasks:
  
   - name: This executes, fails, and the failure is ignored
     ansible.builtin.command: /bin/true
    
   - name: Install packages
     apt:
      name: httpd
      state: present
        
   - name: Write the apache config file
     service:
       name: httpd
       state: started
       enabled: True
      

   - name: Deploy static website
     copy:
       src: index.html
       dest: /var/www/html/
      
...
   
