---
- name: Update web servers
  hosts: webservers
  become: True
 

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum4:
      name: httpd
      state: present
  - name: Write the apache config file
    service:
      name: httpd
      state: started
      enabled: True
      

  - name: Deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
      
 ...
   
