---
- name: Update web servers
  hosts: webservers
  remote_user: root
 

  tasks:
        
  - name: Write the apache config file
    service:
      name: httpd
      state: started
      enabled: True
      

  - name: Deploy static website
    copy:
      src: index.html
      dest: /var/www/html/
      
...
   
